---
- name: Add multiple users with specified passwords
  hosts: defaults
  become: yes
  tasks:
    - name: Add users
      user:
        name: "{{ item.name }}"
        group: root
        password: "{{ item.password }}"
        update_password: on_create
        shell: /bin/bash
      loop:
        - { name: joe, password: "tGY.K.uNb0YNU" }
        - { name: tina, password: "tGY.K.uNb0YNU" }
