---
- name: nas config backup demo
  hosts: newnas
  tasks:
   - name: Create backup directory on each NAS client
     file:
       path: /data/bk
       state: directory
   - name: tar NAS config file
     shell:
       chdir: /data/bk
       cmd: tar fczP freenas-v1.db.tar /data/freenas-v1.db
   - name: fetch config file to master node (local)
     fetch:
       src: /data/bk/freenas-v1.db.tar
       dest: /root/nasbk
   - name: copy installation media from master node to slave node
     copy:
       src: /FreeNAS-11.2-U8-manual-update.tar
       dest: /data/bk/
   - name: perform upgrade on each NAS client
     shell:
       cmd: freenas-update -v /data/bk/FreeNAS-11.2-U8-manual-update.tar
