---
- name: nas config backup demo
  hosts: newnas
  tasks:
   - name: Create backup directory
     file:
       path: /data/bk
       state: directory
   - name: cd and tar
     shell:
       chdir: /data/bk
       cmd: tar fczP freenas-v1.db.tar /data/freenas-v1.db
   - name: fetch tar file to local
     fetch:
       src: /data/bk/freenas-v1.db.tar
       dest: /root/nasbk
   - name: copy installation media from master node to slave node
     copy:
       src: /TrueNAS-13.0-U4-manual-update.tar
       dest: /data/bk/
   - name: upgrade
     shell:
       cmd: freenas-update -v /data/bk/TrueNAS-13.0-U4-manual-update.tar
